SCREEN_SIZE = 800*3, 600*3
FIXED_DT = 1/60
MAX_FRAMERATE = 144

CAM_SCALE_MIN = 2
CAM_SCALE_MAX = 40
CAM_MOVE_SPEED = 1000
CAM_SCALE_SPEED = 30

SIMULATION = "WFC" # BriansBrain, GameOfLife, DoomFire, WFC
RENDERER = "standard" # zypher, bloom, standard
